vegan:
  - "apple"
  - "mushroom_stew"
  - "bread"
  - "golden_apple"
  - "enchanted_golden_apple"
  - "cake"
  - "cookie"
  - "melon_slice"
  - "dried_kelp"
  - "carrot"
  - "potato"
  - "baked_potato"
  - "poisonous_potato"
  - "golden_carrot"
  - "pumpkin_pie"
  - "chorus_fruit"
  - "beetroot"
  - "beetroot_soup"
  - "suspicious_stew"
  - "sweet_berries"
  - "glow_berries"
  - "honey_bottle"
carnivorous:
  - "porkchop"
  - "cooked_porkchop"
  - "cod"
  - "salmon"
  - "tropical_fish"
  - "pufferfish"
  - "cooked_cod"
  - "cooked_salmon"
  - "beef"
  - "cooked_beef"
  - "chicken"
  - "cooked_chicken"
  - "rotten_flesh"
  - "rabbit"
  - "cooked_rabbit"
  - "rabbit_stew"
  - "mutton"
  - "cooked_mutton"
custom:
  - "apple"