name: FoodRestriction
version: 0.1
main: com.brandongcobb.foodrestriction.FoodRestriction
api-version: 1.0
website: www.github.com/brandongrahamcobb
commands:
  leaderboard:
    usage: /leaderboard
    description:
  togglekeepinv:
    usage: /togglekeepinv
    description:
